---

- name: Install nginx
  apt: name=nginx update_cache=yes

- name: create web group
  group: name=web

- name: create web user
  user: name=web group=web comment="User for nginx management"

- name: delete existing sites-available directory
  file: path=/etc/nginx/sites-available state=absent

- name: delete existing sites-enabled directory
  file: path=/etc/nginx/sites-enabled state=absent

- name: create sites-available directory
  file: path=/etc/nginx/sites-available state=directory group=web owner=web mode=0754

- name: create sites-enabled directory
  file: path=/etc/nginx/sites-enabled state=directory group=web owner=web mode=0754

- name: create deployment folder
  file: path={{ website_root }} state=directory mode=0775 group=web owner=web

- name: copy config
  become_user: web
  become: true
  template: src=webserver.conf dest=/etc/nginx/sites-available/webserver.conf

- name: enable config
  become_user: web
  become: true
  file: >
    dest=/etc/nginx/sites-enabled/webserver.conf
    src=/etc/nginx/sites-available/webserver.conf
    state=link
  notify: restart nginx
