---

- name: create web group
  group: name=web

- name: create web user
  user: name=web group=web comment="User for nginx management"

- name: add current user to web group
  user: name={{ ansible_user }} groups=web append=yes

- name: create bash_profile
  become_user: "{{ ansible_user }}"
  become: true
  file: path=~/.bash_profile state=touch mode=0644

- name: add git core ppa
  # TODO: Should this be removed? We should be using https probably
  apt_repository: repo="deb http://ftp.us.debian.org/debian testing main contrib non-free"

- name: check if node upstream is already added
  # TODO: Move this to a variable
  stat: path=/etc/apt/sources.list.d/nodesource.list
  register: nodesourcerepo

- name: Download node remote repository
  shell: wget -qO- https://deb.nodesource.com/setup_6.x | bash -
  when: not nodesourcerepo.stat.exists

# https://github.com/ansible/ansible/issues/18987 IDK
- name: install aptitude
  apt: name=aptitude state=present update_cache=yes

- name: prerequisites for ruby, node, nginx
  apt: name={{ item }} update_cache=yes
  with_items:
    - bison
    - build-essential
    - libffi-dev
    - libncurses5-dev
    - libreadline-dev
    - libssl-dev
    - libyaml-dev
    - zlib1g-dev
    - git
    - npm
    - nodejs
    - ruby
