#!/bin/bash

rm -Rf {{ temp_dir }}
source ~/.bash_profile

git clone {{ repo_dir }} {{ temp_dir }}
cd {{ temp_dir }}

cp -pRPv _site_compiled/* {{ website_root }}
chown -R {{ansible_user}}:{{ansible_user}} {{ website_root }}

exit
rm -Rf {{ temp_dir }}
exit(0)
